version: '2'

services:
  gogs:
    image: gogs/gogs
    volumes:
    - ./gogs:/data
    ports:
    - "10022:22"
    - "10080:3000"

  drone-server:
    image: drone/drone:0.7
    ports:
      - "8000:8000"
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      # - DRONE_HOST=${DRONE_HOST}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_GOGS_SKIP_VERIFY=false

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}